### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy'

### ISSUE THREAD

**Issue by mhotep** [amirpavlo/BYASP#1]
Just installed BYASP. Attempted to enable it and got the following:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Nnamdi\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BYASP-master\__init__.py", line 26, in <module>
    from . import bface
  File "C:\Users\Nnamdi\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BYASP-master\bface.py", line 17, in <module>
    from . import facs_process as facs
  File "C:\Users\Nnamdi\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BYASP-master\facs_process.py", line 4, in <module>
    from scipy.signal import savgol_filter
ModuleNotFoundError: No module named 'scipy'

Is SCIPY required? I didn't read that anywhere in the documentation.

**Comment by amirpavlo** [comment]
Yes it is. What I usually do is install it locally on my system. I use linux So I would do:

`pip3 install scipy`
`cd build_linux/bin/2.91/python/lib/python3.7`
`mv site-packages site-packages.old`
`ln -s /home/<username>/.local/lib/python3.7/site-packages/ site-packages`

Since you installed the packages locally then it should get picked up from your local directory instead of from blenders.

I don't think blender modifies python in anyway so it's safe to just use the standard python, provided they are the same version.

I use scipy in the FACS portion of the add-on to smooth out arrays and such.
